# Generated by Django 4.0.6 on 2022-07-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author'},
        ),
    ]
