# Generated by Django 4.0.6 on 2022-08-03 14:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
